/**
 * Hermes skills provider — reads bundled / auto-generated skills from a
 * Hermes profile's `skills/` directory.
 *
 * Hermes skill layout:
 *   /root/.hermes/profiles/<profile>/skills/
 *     ├── <category>/                 e.g. data-science, creative, mlops
 *     │   ├── DESCRIPTION.md           category description (skipped)
 *     │   ├── <skill-name>/
 *     │   │   ├── SKILL.md             YAML frontmatter + body
 *     │   │   │   ---
 *     │   │   │   name: jupyter-live-kernel
 *     │   │   │   description: >
 *     │   │   │     Use a live Jupyter kernel...
 *     │   │   │   version: 1.0.0
 *     │   │   │   author: Hermes Agent       ← distinguishes bundled vs user
 *     │   │   │   ---
 *     │   │   └── ...
 *
 * Callers see a SkillItem-compatible DTO so the existing SkillsPage UI can
 * render Hermes skills without structural changes.
 */

import { readFileSync, readdirSync, existsSync, statSync } from "fs";
import { join } from "path";

export type HermesSkillItem = {
  id: string;                     // "<category>/<skill_name>"
  name: string;
  description?: string;
  source: "system" | "extra";     // "system" = Hermes 自带 bundled，"extra" = 用户/自动生成
  enabled: true;                  // Hermes 默认加载所有 skills
  enabledForAgent: true;
  category?: string;              // 顶级目录名
  emoji?: string;
  runtime: "hermes";
  meta?: {
    author?: string;
    version?: string;
    createdByLLM?: boolean;       // author 含 "agent" / "llm" / "auto" 即视为自动生成
  };
};

const CATEGORY_EMOJI: Record<string, string> = {
  "data-science": "📊",
  "creative": "🎨",
  "devops": "🛠",
  "diagramming": "📐",
  "email": "✉️",
  "feeds": "📡",
  "gaming": "🎮",
  "gifs": "🎞",
  "github": "🐙",
  "mcp": "🔌",
  "media": "🎥",
  "mlops": "🤖",
  "note-taking": "📝",
  "productivity": "⚡",
  "red-teaming": "🛡",
  "research": "🔬",
  "smart-home": "🏠",
  "social-media": "📱",
  "software-development": "💻",
  "domain": "🌐",
  "apple": "🍎",
  "leisure": "🎲",
  "autonomous-ai-agents": "🤖",
  "inference-sh": "🧠",
  "dogfood": "🐕",
};

/**
 * Parse a SKILL.md YAML frontmatter (the simple subset we care about).
 * We don't pull a full YAML parser — frontmatter here uses only name / description /
 * version / author top-level string fields, which a line-scanner handles safely.
 */
function parseFrontmatter(content: string): Record<string, string> {
  const m = content.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!m) return {};
  const fm: Record<string, string> = {};
  const block = m[1];
  const lines = block.split("\n");
  let currentKey: string | null = null;
  let buf: string[] = [];
  const flush = () => {
    if (currentKey) fm[currentKey] = buf.join(" ").trim();
    currentKey = null;
    buf = [];
  };
  for (const raw of lines) {
    // Only top-level keys (no indent) — nested metadata we don't need.
    const topKey = raw.match(/^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$/);
    if (topKey && !raw.startsWith(" ") && !raw.startsWith("\t")) {
      flush();
      currentKey = topKey[1];
      const val = topKey[2].trim();
      if (val === ">" || val === "|" || val === "") {
        // Multiline value continues in indented lines below.
      } else {
        // Strip surrounding quotes.
        buf.push(val.replace(/^["']|["']$/g, ""));
      }
    } else if (currentKey && (raw.startsWith("  ") || raw.startsWith("\t"))) {
      buf.push(raw.trim());
    }
  }
  flush();
  return fm;
}

function isLikelyAutoGenerated(author: string | undefined): boolean {
  if (!author) return false;
  const a = author.toLowerCase();
  // Hermes bundled 默认 author 是 "Hermes Agent"（大写 A），不判定为 auto
  // auto-generated skill 一般会带 "llm" / "auto" / "generated" 标识或用户自己的名字
  if (a === "hermes agent") return false;
  return /\b(llm|auto|generated)\b/.test(a);
}

/**
 * List all skills under a Hermes profile. Safely no-throws; returns [] on error.
 */
export function listHermesSkills(profileName: string): HermesSkillItem[] {
  const skillsRoot = `/root/.hermes/profiles/${profileName}/skills`;
  if (!existsSync(skillsRoot)) return [];

  const out: HermesSkillItem[] = [];

  let categories: string[];
  try {
    categories = readdirSync(skillsRoot).filter((name) => {
      try {
        return statSync(join(skillsRoot, name)).isDirectory();
      } catch {
        return false;
      }
    });
  } catch {
    return [];
  }

  for (const cat of categories) {
    const catDir = join(skillsRoot, cat);
    let skillDirs: string[];
    try {
      skillDirs = readdirSync(catDir).filter((name) => {
        try {
          return statSync(join(catDir, name)).isDirectory();
        } catch {
          return false;
        }
      });
    } catch {
      continue;
    }

    for (const skillName of skillDirs) {
      const skillDir = join(catDir, skillName);
      const skillMd = join(skillDir, "SKILL.md");
      let fm: Record<string, string> = {};
      let description = "";
      if (existsSync(skillMd)) {
        try {
          const content = readFileSync(skillMd, "utf8");
          fm = parseFrontmatter(content);
          description = String(fm.description || "").replace(/\s+/g, " ").trim();
        } catch {}
      } else {
        // 没 SKILL.md 的 skill 目录依旧列出（README.md or 裸目录）
        const readme = join(skillDir, "README.md");
        if (existsSync(readme)) {
          try {
            const content = readFileSync(readme, "utf8").split("\n").slice(0, 5).join(" ");
            description = content.replace(/^#+\s*/, "").replace(/\s+/g, " ").slice(0, 200).trim();
          } catch {}
        }
      }

      const displayName = String(fm.name || skillName).trim();
      const author = fm.author;
      const auto = isLikelyAutoGenerated(author);

      out.push({
        id: `${cat}/${skillName}`,
        name: displayName,
        description: description.slice(0, 500) || undefined,
        source: auto ? "extra" : "system",
        enabled: true,
        enabledForAgent: true,
        category: cat,
        emoji: CATEGORY_EMOJI[cat] || "🧩",
        runtime: "hermes",
        meta: {
          author,
          version: fm.version,
          createdByLLM: auto,
        },
      });
    }
  }

  // Stable sort: auto-generated 在前（用户更关心新沉淀的），然后按 category / name
  out.sort((a, b) => {
    const aAuto = a.meta?.createdByLLM ? 0 : 1;
    const bAuto = b.meta?.createdByLLM ? 0 : 1;
    if (aAuto !== bAuto) return aAuto - bAuto;
    const cat = (a.category || "").localeCompare(b.category || "");
    if (cat !== 0) return cat;
    return a.name.localeCompare(b.name);
  });

  return out;
}
